name: golang-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golanf:1.22
    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Test
        run: GOOS=linux GOARCH=amd64 go test

      - name: Vet
        run: |
          go vet ./...